name = "schoolsafe-v2-api"
main = "src/index.ts"
compatibility_date = "2026-08-18"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOWED_ORIGINS = "https://schoolsafe-v2.pages.dev,http://127.0.0.1:4175,http://localhost:4175"

[[kv_namespaces]]
binding = "SCHOOLSAFE_CACHE"
id = "1366fb62812040a4892077fbe9b71993"

[[r2_buckets]]
binding = "SCHOOLSAFE_FILES"
bucket_name = "schoolsafe-v2-files"

[[d1_databases]]
binding = "SCHOOLSAFE_ARCHIVE"
database_id = "fe10587c-e9c4-4aea-a34c-dfba055f3adc"

[[queues.producers]]
binding = "SCHOOLSAFE_QUEUE"
queue = "schoolsafe-v2-notifications"

[[queues.consumers]]
queue = "schoolsafe-v2-notifications"

[observability]
enabled = true
